import Image from "next/image";

/**
 * The mark is the orb — the same dotted sphere the app draws while it is
 * listening to you, frozen on one frame. It replaced a four-bar mic level
 * meter, which the app itself no longer uses anywhere.
 *
 * It ships as a raster generated by `Scripts/make-logo.swift` in the app repo,
 * not as hand-authored SVG. Two reasons: the figure is a field of dots whose
 * layout is tuned per display size, so an SVG would be a second copy of the
 * wave painter to keep in step with the app's; and at this size a generic
 * downscale turns the field to mush, which is why the generator draws a
 * dedicated asset for this 24px box.
 *
 * Static on purpose, and `unoptimized` on purpose. `thinking-orbs` renders the
 * live animated version — but a logo must not change shape, the system spends
 * its only perpetual motion on the record dot, and that component is
 * canvas-only, so it would also cost the nav and footer a server-rendered
 * mark. `unoptimized` keeps the exact bytes the generator produced rather than
 * letting the image pipeline resample a dot field.
 */
export function OrbMark({ className = "" }: { className?: string }) {
  return (
    <Image
      src="/wordmark-orb.png"
      alt=""
      aria-hidden="true"
      width={24}
      height={24}
      unoptimized
      priority
      className={`wordmark-mark ${className}`}
    />
  );
}

export function Wordmark({ className = "" }: { className?: string }) {
  return (
    <span className={`wordmark ${className}`}>
      <OrbMark />
      <span className="wordmark-text">
        whisper<em>master</em>
      </span>
    </span>
  );
}
